// College data - 90 colleges total (30 CSE, 30 ECE, 30 MECH)
const sampleColleges = [
    { "name": "JNTU College of Engineering", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 520, "intermediate_marks_cutoff": 92, "affiliation": "State University", "fees": 85000 },
    { "name": "Osmania University Engineering College", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 680, "intermediate_marks_cutoff": 90, "affiliation": "State University", "fees": 90000 },
    { "name": "CBIT", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 1100, "intermediate_marks_cutoff": 88, "affiliation": "Autonomous", "fees": 160000 },
    { "name": "Vasavi College of Engineering", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 1500, "intermediate_marks_cutoff": 87, "affiliation": "Autonomous", "fees": 155000 },
    { "name": "VNR Vignana Jyothi Institute of Engineering", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 2100, "intermediate_marks_cutoff": 85, "affiliation": "Autonomous", "fees": 170000 },
    { "name": "Sreenidhi Institute of Science and Technology", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 2600, "intermediate_marks_cutoff": 84, "affiliation": "Autonomous", "fees": 165000 },
    { "name": "Gokaraju Rangaraju Institute of Engineering", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 3100, "intermediate_marks_cutoff": 83, "affiliation": "Autonomous", "fees": 150000 },
    { "name": "MLR Institute of Technology", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 3600, "intermediate_marks_cutoff": 82, "affiliation": "Private", "fees": 140000 },
    { "name": "Marri Laxman Reddy Engineering College", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 4200, "intermediate_marks_cutoff": 81, "affiliation": "Private", "fees": 135000 },
    { "name": "Institute of Aeronautical Engineering", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 4700, "intermediate_marks_cutoff": 80, "affiliation": "Private", "fees": 130000 },
    { "name": "KMIT", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 5200, "intermediate_marks_cutoff": 82, "affiliation": "Autonomous", "fees": 155000 },
    { "name": "BV Raju Institute of Technology", "location": "Narsapur", "course": "CSE", "mcet_rank_cutoff": 5800, "intermediate_marks_cutoff": 84, "affiliation": "Autonomous", "fees": 140000 },
    { "name": "CVR College of Engineering", "location": "Ibrahimpatnam", "course": "CSE", "mcet_rank_cutoff": 6400, "intermediate_marks_cutoff": 81, "affiliation": "Private", "fees": 135000 },
    { "name": "Anurag University", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 6900, "intermediate_marks_cutoff": 80, "affiliation": "Private", "fees": 150000 },
    { "name": "SR University", "location": "Warangal", "course": "CSE", "mcet_rank_cutoff": 7500, "intermediate_marks_cutoff": 79, "affiliation": "Private", "fees": 165000 },
    { "name": "Kakatiya University Engineering College", "location": "Warangal", "course": "CSE", "mcet_rank_cutoff": 8200, "intermediate_marks_cutoff": 78, "affiliation": "State University", "fees": 85000 },
    { "name": "Guru Nanak Institutions Technical Campus", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 9000, "intermediate_marks_cutoff": 77, "affiliation": "Private", "fees": 120000 },
    { "name": "CMR College of Engineering & Technology", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 9600, "intermediate_marks_cutoff": 76, "affiliation": "Private", "fees": 125000 },
    { "name": "Stanley College of Engineering", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 10500, "intermediate_marks_cutoff": 75, "affiliation": "Private", "fees": 115000 },
    { "name": "Vignana Bharathi Institute of Technology", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 11200, "intermediate_marks_cutoff": 74, "affiliation": "Private", "fees": 120000 },
    { "name": "Malla Reddy Engineering College", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 13000, "intermediate_marks_cutoff": 73, "affiliation": "Private", "fees": 120000 },
    { "name": "ACE Engineering College", "location": "Ghatkesar", "course": "CSE", "mcet_rank_cutoff": 14000, "intermediate_marks_cutoff": 72, "affiliation": "Private", "fees": 110000 },
    { "name": "Sridevi Women's Engineering College", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 15000, "intermediate_marks_cutoff": 71, "affiliation": "Private", "fees": 105000 },
    { "name": "AVN Institute of Engineering & Technology", "location": "Ranga Reddy", "course": "CSE", "mcet_rank_cutoff": 16000, "intermediate_marks_cutoff": 70, "affiliation": "Private", "fees": 100000 },
    { "name": "Mahindra University Ecole Centrale", "location": "Hyderabad", "course": "CSE", "mcet_rank_cutoff": 2000, "intermediate_marks_cutoff": 90, "affiliation": "Private", "fees": 350000 },
    { "name": "JNTU College of Engineering", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 800, "intermediate_marks_cutoff": 90, "affiliation": "State University", "fees": 85000 },
    { "name": "Osmania University Engineering College", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 1300, "intermediate_marks_cutoff": 88, "affiliation": "State University", "fees": 90000 },
    { "name": "CBIT", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 1800, "intermediate_marks_cutoff": 87, "affiliation": "Autonomous", "fees": 150000 },
    { "name": "Vasavi College of Engineering", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 2400, "intermediate_marks_cutoff": 86, "affiliation": "Autonomous", "fees": 145000 },
    { "name": "VNR Vignana Jyothi Institute of Engineering", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 3000, "intermediate_marks_cutoff": 84, "affiliation": "Autonomous", "fees": 155000 },
    { "name": "Sreenidhi Institute of Science and Technology", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 3600, "intermediate_marks_cutoff": 83, "affiliation": "Autonomous", "fees": 150000 },
    { "name": "Gokaraju Rangaraju Institute of Engineering", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 4100, "intermediate_marks_cutoff": 82, "affiliation": "Autonomous", "fees": 140000 },
    { "name": "MLR Institute of Technology", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 4600, "intermediate_marks_cutoff": 81, "affiliation": "Private", "fees": 135000 },
    { "name": "Marri Laxman Reddy Engineering College", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 5100, "intermediate_marks_cutoff": 80, "affiliation": "Private", "fees": 130000 },
    { "name": "Institute of Aeronautical Engineering", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 5600, "intermediate_marks_cutoff": 79, "affiliation": "Private", "fees": 125000 },
    { "name": "KMIT", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 6200, "intermediate_marks_cutoff": 80, "affiliation": "Autonomous", "fees": 150000 },
    { "name": "BV Raju Institute of Technology", "location": "Narsapur", "course": "ECE", "mcet_rank_cutoff": 6800, "intermediate_marks_cutoff": 82, "affiliation": "Autonomous", "fees": 140000 },
    { "name": "CVR College of Engineering", "location": "Ibrahimpatnam", "course": "ECE", "mcet_rank_cutoff": 7400, "intermediate_marks_cutoff": 78, "affiliation": "Private", "fees": 130000 },
    { "name": "Anurag University", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 8200, "intermediate_marks_cutoff": 77, "affiliation": "Private", "fees": 140000 },
    { "name": "SR University", "location": "Warangal", "course": "ECE", "mcet_rank_cutoff": 9000, "intermediate_marks_cutoff": 76, "affiliation": "Private", "fees": 150000 },
    { "name": "Kakatiya University Engineering College", "location": "Warangal", "course": "ECE", "mcet_rank_cutoff": 9800, "intermediate_marks_cutoff": 75, "affiliation": "State University", "fees": 85000 },
    { "name": "Guru Nanak Institutions Technical Campus", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 10500, "intermediate_marks_cutoff": 74, "affiliation": "Private", "fees": 120000 },
    { "name": "CMR College of Engineering & Technology", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 11200, "intermediate_marks_cutoff": 73, "affiliation": "Private", "fees": 115000 },
    { "name": "Stanley College of Engineering", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 12000, "intermediate_marks_cutoff": 72, "affiliation": "Private", "fees": 110000 },
    { "name": "Vignana Bharathi Institute of Technology", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 12800, "intermediate_marks_cutoff": 71, "affiliation": "Private", "fees": 120000 },
    { "name": "Malla Reddy Engineering College", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 14000, "intermediate_marks_cutoff": 70, "affiliation": "Private", "fees": 125000 },
    { "name": "ACE Engineering College", "location": "Ghatkesar", "course": "ECE", "mcet_rank_cutoff": 15000, "intermediate_marks_cutoff": 78, "affiliation": "Private", "fees": 110000 },
    { "name": "Sridevi Women's Engineering College", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 16000, "intermediate_marks_cutoff": 79, "affiliation": "Private", "fees": 105000 },
    { "name": "AVN Institute of Engineering & Technology", "location": "Ranga Reddy", "course": "ECE", "mcet_rank_cutoff": 17000, "intermediate_marks_cutoff": 80, "affiliation": "Private", "fees": 100000 },
    { "name": "Mahindra University Ecole Centrale", "location": "Hyderabad", "course": "ECE", "mcet_rank_cutoff": 3500, "intermediate_marks_cutoff": 89, "affiliation": "Private", "fees": 300000 },
    { "name": "JNTU College of Engineering", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 1500, "intermediate_marks_cutoff": 88, "affiliation": "State University", "fees": 85000 },
    { "name": "Osmania University Engineering College", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 2100, "intermediate_marks_cutoff": 86, "affiliation": "State University", "fees": 90000 },
    { "name": "CBIT", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 3000, "intermediate_marks_cutoff": 85, "affiliation": "Autonomous", "fees": 145000 },
    { "name": "Vasavi College of Engineering", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 3600, "intermediate_marks_cutoff": 84, "affiliation": "Autonomous", "fees": 140000 },
    { "name": "VNR Vignana Jyothi Institute of Engineering", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 4200, "intermediate_marks_cutoff": 83, "affiliation": "Autonomous", "fees": 150000 },
    { "name": "Sreenidhi Institute of Science and Technology", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 4800, "intermediate_marks_cutoff": 82, "affiliation": "Autonomous", "fees": 145000 },
    { "name": "Gokaraju Rangaraju Institute of Engineering", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 5300, "intermediate_marks_cutoff": 81, "affiliation": "Autonomous", "fees": 140000 },
    { "name": "MLR Institute of Technology", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 5800, "intermediate_marks_cutoff": 80, "affiliation": "Private", "fees": 135000 },
    { "name": "Marri Laxman Reddy Engineering College", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 6300, "intermediate_marks_cutoff": 79, "affiliation": "Private", "fees": 130000 },
    { "name": "Institute of Aeronautical Engineering", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 6900, "intermediate_marks_cutoff": 78, "affiliation": "Private", "fees": 125000 },
    { "name": "KMIT", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 7500, "intermediate_marks_cutoff": 77, "affiliation": "Autonomous", "fees": 140000 },
    { "name": "BV Raju Institute of Technology", "location": "Narsapur", "course": "MECH", "mcet_rank_cutoff": 8200, "intermediate_marks_cutoff": 76, "affiliation": "Autonomous", "fees": 130000 },
    { "name": "CVR College of Engineering", "location": "Ibrahimpatnam", "course": "MECH", "mcet_rank_cutoff": 8800, "intermediate_marks_cutoff": 75, "affiliation": "Private", "fees": 125000 },
    { "name": "Anurag University", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 9500, "intermediate_marks_cutoff": 74, "affiliation": "Private", "fees": 130000 },
    { "name": "SR University", "location": "Warangal", "course": "MECH", "mcet_rank_cutoff": 10200, "intermediate_marks_cutoff": 73, "affiliation": "Private", "fees": 140000 },
    { "name": "Kakatiya University Engineering College", "location": "Warangal", "course": "MECH", "mcet_rank_cutoff": 11000, "intermediate_marks_cutoff": 72, "affiliation": "State University", "fees": 85000 },
    { "name": "Guru Nanak Institutions Technical Campus", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 11800, "intermediate_marks_cutoff": 71, "affiliation": "Private", "fees": 120000 },
    { "name": "CMR College of Engineering & Technology", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 12600, "intermediate_marks_cutoff": 70, "affiliation": "Private", "fees": 110000 },
    { "name": "Stanley College of Engineering", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 13300, "intermediate_marks_cutoff": 71, "affiliation": "Private", "fees": 115000 },
    { "name": "Vignana Bharathi Institute of Technology", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 14000, "intermediate_marks_cutoff": 72, "affiliation": "Private", "fees": 120000 },
    { "name": "Malla Reddy Engineering College", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 15000, "intermediate_marks_cutoff": 73, "affiliation": "Private", "fees": 125000 },
    { "name": "ACE Engineering College", "location": "Ghatkesar", "course": "MECH", "mcet_rank_cutoff": 16000, "intermediate_marks_cutoff": 74, "affiliation": "Private", "fees": 110000 },
    { "name": "Sridevi Women's Engineering College", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 17000, "intermediate_marks_cutoff": 75, "affiliation": "Private", "fees": 105000 },
    { "name": "AVN Institute of Engineering & Technology", "location": "Ranga Reddy", "course": "MECH", "mcet_rank_cutoff": 18000, "intermediate_marks_cutoff": 76, "affiliation": "Private", "fees": 100000 },
    { "name": "Mahindra University Ecole Centrale", "location": "Hyderabad", "course": "MECH", "mcet_rank_cutoff": 4000, "intermediate_marks_cutoff": 89, "affiliation": "Private", "fees": 300000 }
];

module.exports = sampleColleges;
